### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by sjdonado** [sjdonado/culefilo#1]
## Design

1. User input: name of your favorite meal (text), post code (text)

2. Zip/Postal Code Lookup -> extract country, city/place name, latitude, longitude https://data.opendatasoft.com/explore/dataset/geonames-postal-code%40public/table/?q=080001

3. [text-generation]: LLM prompts: 
```
"Other names for {favorite meal} in {country}?"
"From where is originally {favorite meal}?"

---

"what's the cousine of {favorite meal}?"
"Is {favorite meal} vegetarian, vegan, gluten-free, lactose-free?"
```

first search: bandeja paisa + location bias -> 6 results ? OK
(no results above?) -> second search: "From where is originally {favorite meal}?" -> 6 results ? OK
third search: "what's the cousine of {favorite meal}?" -> 6 results ? OK
final search: "Is {favorite meal} vegetarian, vegan, gluten-free, lactose-free?" -> 6 results ? OK

Google places API text search with data from (3) https://developers.google.com/maps/documentation/places/web-service/text-search, locationBias with data from (2)

4. From (3) from 6 results -> lookup reviews / overall rating. Ranking

5. [summarization]: short description of the place based on the most relevant reviews

6. Return Top 3 results from (5) and explanation message (6)

## To be discussed

1. which LLM performs best?

## Tentative

v0.0.0
- [x] Happy path -> simple search (only text for now)
- [x] history search page
- [x] show search process messages
- [x] responsive design

v0.1.0
- [x] Results thumbnail 
- [x] post code autocomplete

v1.0.0
- [ ] search filters optional select field: filter by meal type (breakfast, lunch, dinner)
- [ ] search filters currentOpeningHours, priceLevel
- [ ] choose number of results (max 6)
- [ ] sync history search (like duckduckgo, no account)
